---
title: "Translational Research as a learning system"
author: "Merlin Bittlinger"
date: "`r Sys.Date()`"
description: Test. Learn. Repeat.
github-repo: RemNil/remnil.github.io
documentclass: book
link-citations: yes
bibliography: book.bib
site: bookdown::bookdown_site
biblio-style: apalike
url: https://remnil.github.io/
---

# Preface {-}

Metrics to evaluate "translational success" in clinical research provide general incentive structures that determine what learning goal may or may not be achieved by optimizing the success rate of Translational Research. ["Information gain per unit a of accepted research burdens"](https://soundcloud.com/plenarysession/ep223) is a concept introduced to further think about how the current regulatory oversight system learns from past [clinical R&D efforts](https://www.ema.europa.eu/en/human-regulatory/research-development) (work in progress). 

The conceptualization of the [institutional](https://www.youtube.com/watch?v=U_6ear-yORE) and economic structure of clinical development of investigational products are challenging to fully grasp. [Research ethics](https://cioms.ch/shop/product/international-ethical-guidelines-for-health-related-research-involving-humans/) is often focused on particular research such as an individual clinical study. In recent times, there is increasing interest in meta-research perspectives to foster ethical organization and oversight of clinical development. 

On this page, I summarize some of my readings in an unsystematic and eclectic way. The aim is not necessarily to say something entirely new or original, but perhaps someone who finds the way to this place will also find a value in the information discussed.

[Open peer-review](http://www.openreviewtoolkit.org/) is enabled using [hypothes.is](https://web.hypothes.is/). This facilitates sentence-by-sentence annotation from readers directly on this page.
